### PR TITLE
Added the Report module to support the Sectigo /report endpoint

### PR DESCRIPTION
**Pull request by NateWerner**
Added support for available reports from the API.

I implemented a get method to provide a dynamic report name based on the API uri. Then additional methods to run specific reports for the more commonly used reports, abstracting the uri for the report.

This was branched on the most recent addition of Domain, and leverages some of those changes.
These reports were tested at the DRAO access level.

### CODE REVIEW

**Comment by coreone** [comment]
Looks good, but this needs a rebase and squash. Once that's done, it should be good to merge.

**Review by coreone — CHANGES_REQUESTED** [review]
Looks good, but this needs a rebase and squash. Once that's done, it should be good to merge.

**Comment by coreone** [comment]
@NateWerner sorry. Can you rebase this again? There was a linting error that popped up in previous code that blocked this merge that I just fixed.

**Review by coreone — DISMISSED** [review]

**Comment by NateWerner** [comment]
Sure, rebased, I see the latest changes in my branch.

**Review by coreone — APPROVED** [review]

**Pull request merged**
