### PR TITLE
Adding more features support in SSL certificates

### PR DESCRIPTION
**Pull request by trolldbois**
- Support parameters in "Listing SSL Certificates" to allow searching for specific certificates
- Add support for "Get SSL Certificate" by cert sslId

### CODE REVIEW

**Review by lukwam — DISMISSED** [review]

**Comment by coreone** [comment]
@trolldbois sorry it took a while to circle back to this.  Can you rebase on current master as there are conflicts here now.  We are also dropping Python 2.7 support, so that should clear up some of the tests after the rebase as well.

**Comment by ravanapel** [comment]
Any update on this? Anything I can help with? This functionality would be useful for me.

**Comment by rhlin888** [comment]
This functionality would be useful for me as well. Would also like to know if there are any updates.

**Comment by trolldbois** [comment]
@coreone

**Comment by coreone** [comment]
There were a couple comments here that didn't seem to get addressed.  Additionally, we have also transitioned to the `main` branch now, so if you could rebase against that base it should pick up the new GitHub Actions.

**Comment by coreone** [comment]
@trolldbois I updated the base branch to `main`.  Please rebase on that branch.

**Comment by coreone** [comment]
@trolldbois I will approve/merge these changes if you can rebase to resolve the conflict and the remaining comments

**Review by coreone — APPROVED** [review]

**Pull request merged**
